id: performance_rootcause
learningObjectives:
- Solving an issue and testing your fix 
hints:
- Can you see the DB query(ies) that happens behind the scene? Check how many queries do we run for a single request.
- Can we merge some of the DB queries into a single query somehow?
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: You need to Hurry up! I’ve almost reached the buffet, and I don’t want this to be a dinner topic, so let’s **fix the code and push the fix** to production!
        delay: 500

githubActions:
  backend:
    testFile: check_latency.js
    capabilities:
    - autocannon
    - axios
    - seeds

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: Thanks! going over it right away
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Thanks! going over it right away
                delay: 300
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Yes! Go ahead and merge.
                delay: 1500
          - actionId: github_pr_approve
            params:
              person: head-of-rd
              message: Yes!  Go ahead and merge.
        github_pr_workflow_complete_failure:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Hmm, that doesn't seem to fix the issue. Look at the PR checks, the latency is still too high.
                delay: 1500
          - actionId: github_pr_reject
            params:
              person: head-of-rd
              message: Hmm, that doesn't seem to fix the issue. Look at the PR checks, the latency is still too high.
        github_pr_merged:
          do:
          - actionId: finish_step
